version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracker_api
    image: tracker_api
    restart: always
    env_file: 
      - .env
    ports:
      - "5000:${PORT}"